pipeline {
    agent any

 environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
      string(name: 'inventory_file', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
      string(name: 'ansible_tag', defaultValue: '',  description: 'This is the tag to decide what role or playbook to run')
    }

  stages {

     stage("Initial cleanup") {
          steps {
            dir("${WORKSPACE}") {
              deleteDir()
            }
          }
        }
  
    stage('Checkout SCM') {
      steps {
            git branch: 'main', url: 'https://github.com/darey-devops/ansible-project.git'
      }
    }

    stage('Prepare Ansible For Execution') {
      steps {
          sh 'echo ${WORKSPACE}'
          sh 'sed -i \'s/roles_path = \\/var\\/lib\\/jenkins\\/workspace/roles_path = \\/var\\/lib\\/jenkins\\/workspace\\/ansible-project_release-0.0.1\\/roles /g\' deploy/ansible.cfg'
      }
    }
               
    stage('Run Ansible') {
      steps {

            ansiblePlaybook become: true, colorized: true, credentialsId: 'ansible', disableHostKeyChecking: true, installation: 'Ansible', tags: "${ansible_tag}", inventory: "inventory/${inventory_file}", playbook: 'playbooks/site.yml'
      }
    }
    

// stage ('Starting ART job') {
//     build job: 'ansible-project', parameters: [[$class: 'StringParameterValue', name: 'systemname', value: systemname]]
// }
    
  }
}