pipeline {
    agent any


  stages {
    stage('Checkout SCM') {
      steps {
            git branch: 'main', url: 'https://github.com/darey-devops/ansible-project.git'
      }
    }


    stage('Run Ansible') {
      steps {
              ansiblePlaybook become: true, colorized: true, credentialsId: 'ansible', disableHostKeyChecking: true, installation: 'Ansible', inventory: 'inventory/dev', playbook: 'playbooks/site.yml'
      }
    }


    stage('Package') {
      steps {
        script {
          sh 'echo "Package Stage"'
        }
      }
    }
    

    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deploy Stage"'
        }
      }
    }
    

    stage('Clean Up') {
      steps {
        script {
          sh 'echo "Clean Up Stage"'
        }
      }
    

    }
  }
}