pipeline {
    agent any

 environment {
      JENKINS_ANSIBLE_CFG_FILE="${WORKSPACE}/playbooks/ansible.cfg"
    }

  stages {
    stage('Checkout SCM') {
      steps {
            git branch: 'main', url: 'https://github.com/darey-devops/ansible-project.git'
      }
    }


    stage('Run Ansible') {
      steps {
              script{
               export ANSIBLE_CONFIG=${env.JENKINS_ANSIBLE_CFG_FILE}
               sh 'sed -i \'s/roles_path = \\/var\\/lib\\/jenkins\\/workspace/roles = \\/var\\/lib\\/jenkins\\/workspace\\/ansible-project_main\\/roles /g\' deploy/ansible.cfg'
              }
              ansiblePlaybook become: true, colorized: true, credentialsId: 'ansible', disableHostKeyChecking: true, installation: 'Ansible', inventory: 'inventory/dev', playbook: 'playbooks/site.yml'
      }
    }


    stage('Package') {
      steps {
        script {
          sh 'echo "Package Stage"'
          // sh 'echo $WORKSPACE'
        }
      }
    }
    

    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deploy Stage"'
        }
      }
    }
    

    stage('Clean Up') {
      steps {
        script {
          sh 'echo "Clean Up Stage"'
        }
      }
    

    }
  }
}